### ISSUE TITLE
[Bug] OfflinePlayer support for Player Expansion

### ISSUE THREAD

**Issue by DelKatey** [PlaceholderAPI/Player-Expansion#21]
Currently, when used in conjunction with ParseOther, it returns no results for an offline player's %player_displayname%, although it is able to return a result with the %player_uuid% placeholder, as well as the %player_name% placeholder.

It is also unable to get the user's last %player_gamemode%, returning a blank result instead.

**Comment by darbyjack** [comment]
Those are the few methods that can be used while a player is offline.

**Comment by cj89898** [comment]
As Glare said, only a few methods are available for OfflinePlayer. You can see the whole list here: https://helpch.at/docs/1.12.2/org/bukkit/OfflinePlayer.html
You can also see all the methods available for Player here: https://helpch.at/docs/1.12.2/org/bukkit/entity/Player.html

If we wanted to enable you to use all things like displayname and gamemode we would have to be storing every user's data as it was when they last logged off.

I would say give the Essentials Expansion a try since they do store nickname and what not in their data folder. (If you're using Essentials for the display name, that is)
