### ISSUE TITLE
%player_level% not working

### ISSUE THREAD

**Issue by agoniaprivat** [PlaceholderAPI/Player-Expansion#89]
Title says it all. Running purpur 1.20.1

**Comment by Tanguygab** [comment]
Title says nothing at all, how is it "not working" ? Does it not parse (= return `%player_level%` instead of a value), does it return 0 ? does it not return the right number? Are you using the placeholder in a plugin that supports PlaceholderAPI?

In case the placeholder doesn't parse, make sure you downloaded the Player expansion (`/papi ecloud download Player` and `/papi reload`, you can check if it's loaded with `/papi list`)

In case it still doesn't return the correct value, please provide the link you get when running `/papi dump`
